const countryList = {
  "UAE Dirham": "AE",
  "Afghan Afghani": "AF",
  "East Caribbean Dollar": "AG",
  "Albanian Lek": "AL",
  "Armenian Dram": "AM",
  "Netherlands Antillean Guilder": "AN",
  "Angolan Kwanza": "AO",
  "Antarctic Dollar": "AQ",
  "Argentine Peso": "AR",
  "Australian Dollar": "AU",
  "Azerbaijani Manat": "AZ",
  "Bosnia-Herzegovina Convertible Mark": "BA",
  "Barbadian Dollar": "BB",
  "Bangladeshi Taka": "BD",
  "West African CFA Franc": "BE",
  "Bulgarian Lev": "BG",
  "Bahraini Dinar": "BH",
  "Burundian Franc": "BI",
  "Bermudian Dollar": "BM",
  "Brunei Dollar": "BN",
  "Bolivian Boliviano": "BO",
  "Brazilian Real": "BR",
  "Bahamian Dollar": "BS",
  "Norwegian Krone": "BV",
  "Botswana Pula": "BW",
  "Belarusian Ruble": "BY",
  "Belize Dollar": "BZ",
  "Canadian Dollar": "CA",
  "Congolese Franc": "CD",
  "Central African CFA Franc": "CF",
  "Swiss Franc": "CH",
  "Chilean Peso": "CL",
  "Chinese Yuan": "CN",
  "Colombian Peso": "CO",
  "Costa Rican Colón": "CR",
  "Cuban Peso": "CU",
  "Cape Verdean Escudo": "CV",
  "Cypriot Pound": "CY",
  "Czech Koruna": "CZ",
  "Djiboutian Franc": "DJ",
  "Danish Krone": "DK",
  "Dominican Peso": "DO",
  "Algerian Dinar": "DZ",
  "Ecuadorian Sucre": "EC",
  "Estonian Kroon": "EE",
  "Egyptian Pound": "EG",
  "Ethiopian Birr": "ET",
  "Euro": "FR",
  "Fijian Dollar": "FJ",
  "Falkland Islands Pound": "FK",
  "British Pound Sterling": "GB",
  "Georgian Lari": "GE",
  "Guernsey Pound": "GG",
  "Ghanaian Cedi": "GH",
  "Gibraltar Pound": "GI",
  "Gambian Dalasi": "GM",
  "Guinean Franc": "GN",
  "Guatemalan Quetzal": "GT",
  "Guyanese Dollar": "GY",
  "Hong Kong Dollar": "HK",
  "Honduran Lempira": "HN",
  "Croatian Kuna": "HR",
  "Haitian Gourde": "HT",
  "Hungarian Forint": "HU",
  "Indonesian Rupiah": "ID",
  "Israeli New Shekel": "IL",
  "Indian Rupee": "IN",
  "Iraqi Dinar": "IQ",
  "Iranian Rial": "IR",
  "Icelandic Króna": "IS",
  "Jamaican Dollar": "JM",
  "Jordanian Dinar": "JO",
  "Japanese Yen": "JP",
  "Kenyan Shilling": "KE",
  "Kyrgyzstani Som": "KG",
  "Cambodian Riel": "KH",
  "Comorian Franc": "KM",
  "North Korean Won": "KP",
  "South Korean Won": "KR",
  "Kuwaiti Dinar": "KW",
  "Cayman Islands Dollar": "KY",
  "Kazakhstani Tenge": "KZ",
  "Lao Kip": "LA",
  "Lebanese Pound": "LB",
  "Sri Lankan Rupee": "LK",
  "Liberian Dollar": "LR",
  "Lesotho Loti": "LS",
  "Lithuanian Litas": "LT",
  "Latvian Lats": "LV",
  "Libyan Dinar": "LY",
  "Moroccan Dirham": "MA",
  "Moldovan Leu": "MD",
  "Malagasy Ariary": "MG",
  "Macedonian Denar": "MK",
  "Myanmar Kyat": "MM",
  "Mongolian Tögrög": "MN",
  "Macanese Pataca": "MO",
  "Mauritanian Ouguiya": "MR",
  "Maltese Lira": "MT",
  "Mauritian Rupee": "MU",
  "Maldivian Rufiyaa": "MV",
  "Malawian Kwacha": "MW",
  "Mexican Peso": "MX",
  "Malaysian Ringgit": "MY",
  "Mozambican Metical": "MZ",
  "Namibian Dollar": "NA",
  "CFP Franc": "NC",
  "Nigerian Naira": "NG",
  "Nicaraguan Córdoba": "NI",
  "Nepalese Rupee": "NP",
  "New Zealand Dollar": "NZ",
  "Omani Rial": "OM",
  "Panamanian Balboa": "PA",
  "Peruvian Sol": "PE",
  "Papua New Guinean Kina": "PG",
  "Philippine Peso": "PH",
  "Pakistani Rupee": "PK",
  "Polish Złoty": "PL",
  "Paraguayan Guaraní": "PY",
  "Qatari Riyal": "QA",
  "Romanian Leu": "RO",
  "Serbian Dinar": "RS",
  "Russian Ruble": "RU",
  "Rwandan Franc": "RW",
  "Saudi Riyal": "SA",
  "Solomon Islands Dollar": "SB",
  "Seychellois Rupee": "SC",
  "Sudanese Pound": "SD",
  "Swedish Krona": "SE",
  "Singapore Dollar": "SG",
  "Slovak Koruna": "SK",
  "Sierra Leonean Leone": "SL",
  "Somali Shilling": "SO",
  "Surinamese Dollar": "SR",
  "São Tomé and Príncipe Dobra": "ST",
  "Salvadoran Colón": "SV",
  "Syrian Pound": "SY",
  "Swazi Lilangeni": "SZ",
  "Thai Baht": "TH",
  "Tajikistani Somoni": "TJ",
  "Turkmenistani Manat": "TM",
  "Tunisian Dinar": "TN",
  "Tongan Paʻanga": "TO",
  "Turkish Lira": "TR",
  "Trinidad and Tobago Dollar": "TT",
  "New Taiwan Dollar": "TW",
  "Tanzanian Shilling": "TZ",
  "Ukrainian Hryvnia": "UA",
  "Ugandan Shilling": "UG",
  "United States Dollar": "US",
  "Uruguayan Peso": "UY",
  "Uzbekistani Som": "UZ",
  "Venezuelan Bolívar": "VE",
  "Vietnamese Đồng": "VN",
  "Vanuatu Vatu": "VU",
  "Yemeni Rial": "YE",
  "South African Rand": "ZA",
  "Zambian Kwacha": "ZM",
  "Zimbabwean Dollar": "ZW"
};