const countryList = {
  "United Arab Emirates (AED - UAE Dirham)": "AE",
  "Afghanistan (AFN - Afghan Afghani)": "AF",
  "Albania (ALL - Albanian Lek)": "AL",
  "Argentina (ARS - Argentine Peso)": "AR",
  "Australia (AUD - Australian Dollar)": "AU",
  "Bangladesh (BDT - Bangladeshi Taka)": "BD",
  "Brazil (BRL - Brazilian Real)": "BR",
  "Canada (CAD - Canadian Dollar)": "CA",
  "China (CNY - Chinese Yuan)": "CN",
  "Egypt (EGP - Egyptian Pound)": "EG",
  "France (EUR - Euro)": "FR",
  "Germany (EUR - Euro)": "DE",
  "India (INR - Indian Rupee)": "IN",
  "Indonesia (IDR - Indonesian Rupiah)": "ID",
  "Japan (JPY - Japanese Yen)": "JP",
  "Malaysia (MYR - Malaysian Ringgit)": "MY",
  "Mexico (MXN - Mexican Peso)": "MX",
  "Nepal (NPR - Nepalese Rupee)": "NP",
  "New Zealand (NZD - New Zealand Dollar)": "NZ",
  "Pakistan (PKR - Pakistani Rupee)": "PK",
  "Philippines (PHP - Philippine Peso)": "PH",
  "Qatar (QAR - Qatari Riyal)": "QA",
  "Russia (RUB - Russian Ruble)": "RU",
  "Saudi Arabia (SAR - Saudi Riyal)": "SA",
  "Singapore (SGD - Singapore Dollar)": "SG",
  "South Africa (ZAR - South African Rand)": "ZA",
  "South Korea (KRW - South Korean Won)": "KR",
  "Sri Lanka (LKR - Sri Lankan Rupee)": "LK",
  "Switzerland (CHF - Swiss Franc)": "CH",
  "Thailand (THB - Thai Baht)": "TH",
  "Turkey (TRY - Turkish Lira)": "TR",
  "United Kingdom (GBP - Pound Sterling)": "GB",
  "United States (USD - US Dollar)": "US",
  "Vietnam (VND - Vietnamese Dong)": "VN",
  "Zimbabwe (ZWD - Zimbabwe Dollar)": "ZW"
};